### ISSUE TITLE
error: " *** No rule to make target 'rfftwnd.pdf', needed by 'fftw3.info'.  Stop."

### ISSUE THREAD

**Issue by YukihiroKomura** [fujitsu/fftw3#1]
When "make -j 30" is executed according to the procedure of "Native compilation using Fujitsu compiler (AArch64 target).", the following error occurs.

"...
make[2]: Entering directory '/home/fx700user/komura/fftw_test/fftw3/mpi'
sed 's/C_MPI_FINT//' ./fftw3-mpi.f03.in > fftw3-mpi.f03
sed 's/C_MPI_FINT//' ./fftw3l-mpi.f03.in > fftw3l-mpi.f03
make  all-am
make[3]: Entering directory '/home/fx700user/komura/fftw_test/fftw3/mpi'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/fx700user/komura/fftw_test/fftw3/mpi'
make[2]: Leaving directory '/home/fx700user/komura/fftw_test/fftw3/mpi'
Making all in doc
make[2]: Entering directory '/home/fx700user/komura/fftw_test/fftw3/doc'
Making all in FAQ
make[3]: Entering directory '/home/fx700user/komura/fftw_test/fftw3/doc/FAQ'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/fx700user/komura/fftw_test/fftw3/doc/FAQ'
make[3]: Entering directory '/home/fx700user/komura/fftw_test/fftw3/doc'
make[3]: *** No rule to make target 'rfftwnd.pdf', needed by 'fftw3.info'.  Stop.
make[3]: Leaving directory '/home/fx700user/komura/fftw_test/fftw3/doc'
make[2]: *** [Makefile:633: all-recursive] Error 1
make[2]: Leaving directory '/home/fx700user/komura/fftw_test/fftw3/doc'
make[1]: *** [Makefile:729: all-recursive] Error 1
make[1]: Leaving directory '/home/fx700user/komura/fftw_test/fftw3'
make: *** [Makefile:573: all] Error 2"

Could you tell me how to deal with it?
Thank you in advance.

**Comment by saosudo** [comment]
The fftw library can be installed even if the doc build fails, but I'll fix it.

The reason for this is that when maintainer-mode generates the files, there was not enough stuff under the doc directory.

**Comment by saosudo** [comment]
This issue was fixed in [043cd0e](https://github.com/fujitsu/fftw3/commit/043cd0ef33f380ee53ecebf8ef3d04225ad8ac9b).
If this is solved in your environment, please click the "Close issue" button.

**Comment by YukihiroKomura** [comment]
Thank you for dealing with it.
I immediately tried the build with the source of https://github.com/fujitsu/fftw3/commit/043cd0ef33f380ee53ecebf8ef3d04225ad8ac9b, and it was built without error.
Thank you for your prompt action.
As there are no more errors, I close this issue.
